name: twitter_news_feed
description: News outlets' tweets
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+5
  flutter_svg: ^1.1.6
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  json_annotation: ^4.8.0
  twitter_api:
    path: packages/twitter_api
  twitter_icons:
    path: packages/twitter_icons

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.0
  mobx_codegen: ^2.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: HelveticaNeueLTPro
      fonts:
        - asset: assets/fonts/HelveticaNeueLTPro/HelveticaNeueLTPro-75Bold.otf
          weight: 700