/// Flutter icons TwitterIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
import 'package:flutter/widgets.dart';

abstract class TwitterIcons {
  static const _family = 'TwitterIcons';
  static const _package = 'twitter_icons';

  static const like =
      IconData(0xe800, fontFamily: _family, fontPackage: _package);
  static const reply =
      IconData(0xe801, fontFamily: _family, fontPackage: _package);
  static const retweet =
      IconData(0xe802, fontFamily: _family, fontPackage: _package);
}
